@baseUrl = http://localhost:8000/api

# products
###
# @name getAll
@resourseName = products
GET {{baseUrl}}/{{resourseName}}

###
# @name filterProducts
GET {{baseUrl}}/{{resourseName}}?color=teal&price_gte=&price_lte=1800000

###
# @name filterProducts
GET {{baseUrl}}/{{resourseName}}?name_like=Win

###
# @name pagination
GET {{baseUrl}}/{{resourseName}}?page=1&_limit=7

###
# @name sortDESC
GET {{baseUrl}}/{{resourseName}}?_sort=price&_order=desc

###
# @name sortASC
GET {{baseUrl}}/{{resourseName}}?_sort=price&_order=asc
 

###
# @name addNew

POST {{baseUrl}}/{{resourseName}} 
Content-Type: application/json

  {
    "categoryId": "1111",
    "name": "Incredible Plastic Hat",
    "color": "lime",
    "price": 226,
    "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    "thumbnailUrl": "http://placeimg.com/400/400",
    "comments": [{"message": "aaaaa"}]
  }

###
# @name update
PATCH {{baseUrl}}/{{resourseName}}/13
Content-Type: application/json

{
   "rating" : []
}

###
# @name remove
DELETE {{baseUrl}}/{{resourseName}}/2 

